# Generated by Django 2.2.24 on 2023-02-10 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0004_auto_20230210_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain_text', models.TextField(verbose_name='Текст жалобы')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_info', to=settings.AUTH_USER_MODEL, verbose_name='Кто жалуется')),
                ('flat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flat_info', to='property.Flat', verbose_name='Квартира в жалобе')),
            ],
        ),
    ]
