# Generated by Django 2.2.24 on 2023-02-12 11:36

import phonenumbers
from django.db import migrations


def create_pure_owner_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    all_flats = Flat.objects.all()
    if not all_flats.exists():
        return
    for flat in all_flats.iterator():
        owners_phonenumber = flat.owners_phonenumber
        parsing_phone_number = phonenumbers.parse(owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(parsing_phone_number):
            pure_owner_phone_number = phonenumbers.format_number(
                parsing_phone_number, phonenumbers.PhoneNumberFormat.INTERNATIONAL)
            flat.owner_pure_phone = pure_owner_phone_number
        flat.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.all().update(owner_pure_phone=None)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(create_pure_owner_number, move_backward),
    ]
