# Generated by Django 2.2.24 on 2023-02-12 11:36

from django.db import migrations
import phonenumbers


def create_pure_owner_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        owners_phonenumber = flat.owners_phonenumber
        parsing_phone_number = phonenumbers.parse(owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(parsing_phone_number):
            pure_owner_phone_number = phonenumbers.format_number(
                parsing_phone_number, phonenumbers.PhoneNumberFormat.INTERNATIONAL)
            flat.owner_pure_phone = pure_owner_phone_number
        flat.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_pure_phone = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(create_pure_owner_number, move_backward),
    ]
