# Generated by Django 2.2.24 on 2023-02-12 12:28

from django.db import migrations


def add_owners_from_flat(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    all_flats = Flat.objects.all()
    if not all_flats.exists():
        return
    for flat in all_flats.iterator():
        Owner.objects.get_or_create(
            owner_name=flat.owner, owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone, )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_owner'),
    ]

    operations = [
        migrations.RunPython(add_owners_from_flat),
    ]
